name: 'Louwers & Partners'
favicon: null
layout_spectrum: 0.2641985542140901
typography_spectrum: 0.7627102781552821
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.8051008100155741
  lightness: 0.7955813249573112
  saturation: 0.8213296311441809
  rhythmicContrast: 0.19451674656011164
purpose: []
